import csv
import io
import json
import logging

logger = logging.getLogger(__name__)


def export_as_text(post: dict, generated: dict) -> str:
    lines = [
        f"ContentAI Export",
        f"{'=' * 50}",
        f"Date: {post.get('created_at', 'N/A')}",
        f"Media Type: {post.get('media_type', 'N/A')}",
        f"Original Text: {post.get('original_text', 'N/A')}",
        "",
        "Generated Content:",
        f"{'-' * 50}",
    ]
    field_labels = {
        "caption": "Caption",
        "hashtags": "Hashtags",
        "keywords": "Keywords",
        "emojis": "Emojis",
        "cta": "Call to Action",
        "hook": "Hook",
        "seo_tags": "SEO Tags",
        "summary": "Summary",
        "translation": "Translation",
    }
    for key, label in field_labels.items():
        value = generated.get(key, "")
        if value:
            lines.append(f"\n{label}:\n{value}")

    lines.append(f"\n{'=' * 50}")
    lines.append("Generated by ContentAI")
    return "\n".join(lines)


def export_as_csv(posts: list) -> str:
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        "ID", "Date", "Media Type", "Original Text",
        "Caption", "Hashtags", "Keywords", "Emojis", "CTA",
        "Hook", "SEO Tags", "Summary", "Translation",
    ])
    for item in posts:
        post = item.get("post", {})
        gen = item.get("generated") or {}
        writer.writerow([
            post.get("id", ""),
            post.get("created_at", ""),
            post.get("media_type", ""),
            post.get("original_text", ""),
            gen.get("caption", ""),
            gen.get("hashtags", ""),
            gen.get("keywords", ""),
            gen.get("emojis", ""),
            gen.get("cta", ""),
            gen.get("hook", ""),
            gen.get("seo_tags", ""),
            gen.get("summary", ""),
            gen.get("translation", ""),
        ])
    return output.getvalue()


def export_as_docx(post: dict, generated: dict) -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor
    from io import BytesIO

    doc = Document()
    title = doc.add_heading("ContentAI Export", 0)
    doc.add_paragraph(f"Date: {post.get('created_at', 'N/A')}")
    doc.add_paragraph(f"Media Type: {post.get('media_type', 'N/A')}")
    if post.get("original_text"):
        doc.add_paragraph(f"Original Text: {post.get('original_text')}")

    doc.add_heading("Generated Content", level=1)
    field_labels = {
        "caption": "Caption",
        "hashtags": "Hashtags",
        "keywords": "Keywords",
        "emojis": "Emojis",
        "cta": "Call to Action",
        "hook": "Hook",
        "seo_tags": "SEO Tags",
        "summary": "Summary",
        "translation": "Translation",
    }
    for key, label in field_labels.items():
        value = generated.get(key, "")
        if value:
            doc.add_heading(label, level=2)
            doc.add_paragraph(value)

    doc.add_paragraph("")
    p = doc.add_paragraph("Generated by ContentAI")
    p.runs[0].italic = True

    buf = BytesIO()
    doc.save(buf)
    return buf.getvalue()


def export_as_pdf(post: dict, generated: dict) -> bytes:
    from io import BytesIO
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
    from reportlab.lib import colors

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("ContentAI Export", styles["Title"]))
    elements.append(Spacer(1, 6 * mm))
    elements.append(Paragraph(f"Date: {post.get('created_at', 'N/A')}", styles["Normal"]))
    elements.append(Paragraph(f"Media Type: {post.get('media_type', 'N/A')}", styles["Normal"]))
    if post.get("original_text"):
        elements.append(Paragraph(f"Original Text: {post.get('original_text')}", styles["Normal"]))
    elements.append(Spacer(1, 6 * mm))

    elements.append(Paragraph("Generated Content", styles["Heading2"]))
    elements.append(Spacer(1, 4 * mm))

    field_labels = {
        "caption": "Caption", "hashtags": "Hashtags", "keywords": "Keywords",
        "emojis": "Emojis", "cta": "Call to Action", "hook": "Hook",
        "seo_tags": "SEO Tags", "summary": "Summary", "translation": "Translation",
    }
    for key, label in field_labels.items():
        value = generated.get(key, "")
        if value:
            elements.append(Paragraph(f"<b>{label}</b>", styles["Normal"]))
            elements.append(Paragraph(value, styles["Normal"]))
            elements.append(Spacer(1, 2 * mm))

    elements.append(Spacer(1, 6 * mm))
    elements.append(Paragraph("Generated by ContentAI", styles["Italic"]))

    doc.build(elements)
    return buf.getvalue()


def export_as_json(post: dict, generated: dict) -> str:
    data = {
        "export_version": "1.0",
        "generated_by": "ContentAI",
        "post": {
            "id": post.get("id"),
            "media_type": post.get("media_type"),
            "original_text": post.get("original_text"),
            "created_at": post.get("created_at"),
        },
        "generated_content": {
            "caption": generated.get("caption", ""),
            "long_caption": generated.get("long_caption", ""),
            "short_caption": generated.get("short_caption", ""),
            "funny_caption": generated.get("funny_caption", ""),
            "professional_caption": generated.get("professional_caption", ""),
            "travel_caption": generated.get("travel_caption", ""),
            "business_caption": generated.get("business_caption", ""),
            "food_caption": generated.get("food_caption", ""),
            "luxury_caption": generated.get("luxury_caption", ""),
            "carousel_text": generated.get("carousel_text", ""),
            "thumbnail_text": generated.get("thumbnail_text", ""),
            "alt_text": generated.get("alt_text", ""),
            "hashtags": generated.get("hashtags", ""),
            "keywords": generated.get("keywords", ""),
            "emojis": generated.get("emojis", ""),
            "cta": generated.get("cta", ""),
            "hook": generated.get("hook", ""),
            "reel_title": generated.get("reel_title", ""),
            "seo_tags": generated.get("seo_tags", ""),
            "summary": generated.get("summary", ""),
            "translation": generated.get("translation", ""),
            "viral_score": generated.get("viral_score", 0),
            "viral_score_reason": generated.get("viral_score_reason", ""),
        },
    }
    return json.dumps(data, indent=2, ensure_ascii=False)
